<?php
include "../controladores/conexionBD.php";

function crearBD(){
	$cnn= new conexion();//crea instancia de la clase conexion
	$con =$cnn->conectar();//la clase conexion almacenada de cnn ejecuta la funcion conectar.



	$sql="CREATE DATABASE sides";//comando sql crea BD
	mysqli_query($con,$sql);//mysql_query(conexion,consulta);
	mysqli_close($con);
}

function crearTablas(){
	$cnn= new conexion();//crea instancia de la clase conexion
	$con =$cnn->conectar();//la clase conexion almacenada de cnn ejecuta la funcion conectar.
	mysqli_select_db($con,"sides");//mysqli_select_db(variableconexion,nombreBD)

//-------------------------------TABLE GRUPO----------------------------------
		$TB_GRUPO = "CREATE TABLE grupo (
		id_grupo INT NOT NULL AUTO_INCREMENT,
		grupo VARCHAR(60),
		puntos INT,
		PRIMARY KEY(id_grupo)
		)";

		if(mysqli_query($con, $TB_GRUPO)){
			echo "<br> - TABLA GRUPO CREADA -";

			$INSERT_GRUPO_TEST = "INSERT INTO
			grupo(id_grupo,grupo,puntos)
			VALUES ('','GRUPO I: SANCIONADA CON 1 PUNTO.','1'),
						 ('','GRUPO II: SANCIONADAS CON 2 PUNTOS','2'),
						 ('','GRUPO III: SANCIONADAS CON 3 PUNTOS.','3'),
						 ('','GRUPO IV: SANCIONADAS CON 4 PUNTOS','4'),
						 ('','GRUPO V: SANCIONADAS CON 5 PUNTOS','5'),
						 ('','GRUPO VI: SANCIONADAS CON 6 PUNTOS','6'),
						 ('','GRUPO VII: SANCIONADAS CON 7 PUNTOS','7')";

			if (mysqli_query($con, $INSERT_GRUPO_TEST)) {
				# code...
				echo "<br> - GRUPOS TESTS INSERTADOS - <br>";
			}
		}

//-------------------------------TABLE FALTA----------------------------------
	$TB_FALTA = "CREATE TABLE falta (
	id_falta INT NOT NULL AUTO_INCREMENT,
	nombre VARCHAR(150),
	id_grupo INT,
	PRIMARY KEY(id_falta)
	)";
	if(mysqli_query($con,$TB_FALTA)){
		echo "<br> - TABLA FALTA CREADA -";

		$INSERT_FALTA_TEST = "INSERT INTO
		falta(id_falta,nombre,id_grupo)
		VALUES ('','ATRASARSE A FORMACION','1'),
					 ('','MOVERSE EN FILAS','1'),
					 ('','FALTA DE POSTURA MILITAR','1'),
					 ('','DESASEADO','1'),
					 ('','DESORDENADO CON SUS EFECTOS PERSONALES','1'),
					 ('','FALTA DE URBANIDAD','1'),
					 ('','HABLAR EN FILAS','1'),
					 ('','ATRASARSE AL PARTE','1'),
					 ('','LLEVAR O CONSUMIR ALIMENTOS EN AULAS O EN FILAS','1'),
					 ('','NO PEDIR PERMISO PARA PASAR O RETIRARSE DE UN RECINTO','1'),
					 ('','NO GRITAR ATENCION CUANDO INGRESA UN SUPERIOR','1'),
					 ('','DESCONOCIMIENTO DE LA JERARQUIA','1'),
					 ('','DESCUIDADO CON EL UNIFORME','1'),
					 ('','MAL TENDIDO DE CAMAS','1'),
					 ('','NO ACUDIR CON PRESTEZA AL LLAMADO DE UN SUPERIOR','1'),
					 ('','NO PEDIR PERMISO PARA CONTINUAR','1'),
					 ('','RETIRARSE O INCORPORARSE A FORMACION SIN PEDIR PERMISO','1'),
					 ('','CARECER DE UTILES DE LIMPIEZA DE ARMAS','1'),
					 ('','CARECER DE UTILES DE ASEO PAÑUELOS TRAPO DE CALZADO HILO AGUJAS','1'),
					 ('','VOTAR BASURA EN LUGARES INDEBIDOS','1'),
					 ('','NO CUMPLIR CON EL HORARIO DE ENCENDIDO Y APAGADO DE LUCES','1'),
					 ('','BOSTEZAR EN FILAS JUGAR EN FILAS','1'),
					 ('','REIR EN FILAS','1'),
					 ('','FALTA DE POSTURA MILITAR','1'),
					 ('','DESATENTO','1'),
					 ('','DESCUIDADO CON LAS PRENDAS DE DOTACION','1'),
					 ('','DESCUIDADO CON LOS PUPITRES','1'),
					 ('','DESATENTO EN CLASES','1'),
					 ('','ATRASARSE EN EL INGRESO AL AULA','1'),
					 ('','NO LLEVAR EL MATERIAL NECESARIO PARA LA MATERIA REGLAMENTO O DOSIER','1'),
					 ('','PONER APODOS OFENSIVOS A LOS SUBALTERNOS Y O CAMARADAS','2'),
					 ('','FALTA DE CORTESIA MILITAR','2'),
					 ('','FALTA DE RESPETO CON LOS CAMARADAS DE CURSO','2'),
					 ('','FALTA DE CONSIDERACION CON EL QUE ESTA AL MANDO','2'),
					 ('','FALTA DE CUIDADO CON LOS JARDINES DEL INSTITUTO','2'),
					 ('','DESCONOCIMIENTO DE LA REGLAMENTACION INTERNA DEL INSTITUTO','2'),
					 ('','FALTA DE SERIEDAD CON LOS ACTOS DE SERVICIO','2'),
					 ('','NO REALIZAR BIEN UN EJERCICIO','2'),
					 ('','PRESTAR PRENDAS MILITARES DE DOTACION SIN AUTORIZACION','2'),
					 ('','FALTA DE CAMARADERIA','2'),
					 ('','NO PRESENTAR PRENDAS EN LA REVISIÓN DE VESTUARIO Y EQUIPO','2'),
					 ('','NO CUMPLIR CORRECTAMENTE UNA SANCION','2'),
					 ('','NO DAR CUMPLIMIENTO A LAS PRESCRIPCIONES MEDICAS ESTABLECIDAS','2'),
					 ('','REALIZAR MOVIMIENTOS Y GESTOS OBSCENOS','2'),
					 ('','NEGLIGENTE','2'),
					 ('','MANIFESTAR DESPRECIO POR LOS ALIMENTOS SUMINISTRADOS EN EL COMEDOR','2'),
					 ('','ALTERAR EL UNIFORME','2'),
					 ('','INTIMAR CON LOS EMPLEADOS CIVILES Y PERSONAL DE SERVICIOS','2'),
					 ('','MANTENER PUBLICA FAMILIARIDAD CON LOS SUBALTERNOS','2'),
					 ('','NO CUMPLIR CON SUS OBLIGACIONES COMO ENCARGADO DE DORMITORIO','2'),
					 ('','NO CUMPLIR CON SUS OBLIGACIONES COMO ENCARGADO DE PABELLON','2'),
					 ('','NO CUMPLIR CON SUS OBLIGACIONES COMO ALUMNO DE SERVICIO','2'),
					 ('','FALTA DE CONTROL CON SU UNIDAD','2'),
					 ('','NO PRESENTARSE A UN SUPERIOR DESPUES DE HABER RECIBIDO UNA ORDEN','2'),
					 ('','INTIMAR CON SUBALTERNOS EN ACTOS DEL SERVICIO O FUERA DE EL','2'),
					 ('','FALTA DE INTERES EN INSTRUCCION','2'),
					 ('','FALTA DE ESPIRITU DE CUERPO','2'),
					 ('','NO RESPETAR EL SUEÑO DE SUS CAMARADAS DESPUES DEL TOQUE DE SILENCIO','2'),
					 ('','IMPONER SANCIONES INMEDIATAS DENTRO DE LOS COMEDORES Y SANIDAD','2'),
					 ('','INSULTAR A UN CAMARADA','2'),
					 ('','ESCUPIR EN LUGARES INDEBIDOS','2'),
					 ('','NO REPETIR EN VOZ ALTA LA ORDEN IMPARTIDA POR UN SUPERIOR','2'),
					 ('','NO LLEVAR CORRECTAMENTE EL UNIFORME','2'),
					 ('','NO DAR CUMPLIMIENTO AL HORARIO','2'),
					 ('','NO CONTESTAR EL SALUDO DE LOS SUBALTERNOS','2'),
					 ('','NO CONDUCIR CORRECTAMENTE SU UNIDAD','2'),
					 ('','NO PRESENTARSE CON SU PAPELETA PARA ENTRAR EN REPOSO','2'),
					 ('','NO VESTIR EL UNIFORME PRESCRITO','2'),
					 ('','NO PERMANECER CON SU UNIDAD','2'),
					 ('','INDIFERENTE','2'),
					 ('','EXPRESARSE EN LENGUAJE OBSCENO','2'),
					 ('','FUMAR','2'),
					 ('','ASUMIR ATRIBUCIONES QUE NO LE CORRESPONDEN','2'),
					 ('','ARBITRARIO','2'),
					 ('','EXCEDERSE EN SUS ATRIBUCIONES','2'),
					 ('','VESTIR UNIFORME EN LUGARES NO RECOMENDABLES','2'),
					 ('','DESCUIDADO CON EL MATERIAL DEPORTIVO','2'),
					 ('','JUGAR EN FORMACION','2'),
					 ('','FALTA DE INSTRUCCION','2'),
					 ('','NO DAR CORRECTAMENTE LAS VOCES DE MANDO','2'),
					 ('','USO DE MAQUILLAJE PINTURA DE LABIOS CEJAS','2'),
					 ('','PINTARSE LAS UÑAS','2'),
					 ('','UTILIZAR ARETES NO REGLAMENTARIOS','2'),
					 ('','NO LLEVAR ZAPATOS REGLAMENTARIOS TACO MEDIANO MODELO CLASICO DE CUERO NEGRO','2'),
					 ('','PERMANECER SIN AUTORIZACION INMEDIACIONES O DENTRO DEL PABELLON DE ALUMNAS(OS)','2'),
					 ('','UTILIZAR JOYAS VISTIENDO UNIFORMES ANILLOS COLLARES PULSERAS','2'),
					 ('','USAR TINTES DE CABELLO PARA ALTERAR EL COLOR NATURAL DEL MISMO','2'),
					 ('','DESPRECIAR LOS ALIMENTOS DEL COMEDOR','2'),
					 ('','PROVOCAR DESORDEN EN AULAS','2'),
					 ('','NO CUMPLIR CON SUS OBLIGACIONES COMO ENCARGADO DE CURSO','2'),
					 ('','NO CUMPLIR CON SUS OBLIGACIONES COMO ENCARGADO DE LIMPIEZA','2'),
					 ('','NO DEVOLVER LIBROS A LA BIBLIOTECA EN EL PLAZO ESTABLECIDO','2'),
					 ('','NO PORTAR SUS UTILES DE ESTUDIO','2'),
					 ('','FALTA DE CUIDADO CON LAS DEPENDENCIAS DEL INSTITUTO','3'),
					 ('','PRESTARSE PRENDAS CIVILES O MILITARES DE LOS SUBALTERNOS','3'),
					 ('','TENENCIA DE LIBROS FOLLETOS U OBJETOS PORNOGRAFICOS','3'),
					 ('','NO PAGAR SUS DEUDAS EN OPORTUNIDAD DENTRO Y FUERA DEL INSTITUTO','3'),
					 ('','ABUSO DE AUTORIDAD CON EL PERSONAL CIVIL Y SOLDADOS','3'),
					 ('','FALTA DE CONSIDERACION CON EL ALUMNO DE SERVICIO DEL BATALLON','3'),
					 ('','FALTA DE CONSIDERACION CON EL AUXILIAR DE SERVICIO DEL BATALLON','3'),
					 ('','FALTA DE CONSIDERACION CON LOS ALUMNOS QUE CUMPLEN EL SERVICIO DE GUARDIA','3'),
					 ('','FALTA DE ESPIRITU MILITAR','3'),
					 ('','NO CUMPLIR CORRECTAMENTE SUS OBLIGACIONES EN LA GUARDIA','3'),
					 ('','FALTA DE CARACTER Y FIRMEZA EN EL MANDO','3'),
					 ('','MANIFESTAR COMPORTAMIENTO ANTIDEPORTIVO EN COMPETENCIAS DEPORTIVAS','3'),
					 ('','IMPONER SANCIONES FISICAS DESPUES DE LOS ALIMENTOS','3'),
					 ('','ABANDONAR LAS INMEDIACIONES DE ENFERMERIA O LA SALA DEL HOSPITAL SIN AUTORIZACION','3'),
					 ('','NO INCORPORARSE A LA ESCUELA DESPUES DE SER DADO DE ALTA DEL HOSPITAL O COSSMIL','3'),
					 ('','RIDICULIZAR A UN SUBALTERNO','3'),
					 ('','NO DAR PARTE OPORTUNAMENTE','3'),
					 ('','ATRASARSE HASTA 30 MINUTOS AL RELEVO DE GUARDIA','3'),
					 ('','ATRASARSE HASTA 30 MINUTOS A CUMPLIR UN ARRESTO','3'),
					 ('','ATRASARSE HASTA 30 MINUTOS AL PARTE DE INCORPORACION DE FRANCOS Y SALIDAS POR ASUNTOS DEL SERVICIO','3'),
					 ('','DAR MAL USO A LOS JARDINES DEL INSTITUTO','3'),
					 ('','ELUDIR EL SALUDO A UN SUPERIOR','3'),
					 ('','REALIZAR RECLAMOS INFUNDADOS','3'),
					 ('','ALTERAR EL UNIFORME ESTABLECIDO PARA EL SERVICIO DE GUARDIA','3'),
					 ('','PERMANECER EN LA CANTINA EN HORAS INDEBIDAS','3'),
					 ('','PROLONGAR O ABREVIAR SANCIONES','3'),
					 ('','DAR MAL EJEMPLO','3'),
					 ('','NO LLEVAR LA PLACA DE IDENTIFICACION PERSONAL','3'),
					 ('','FALTA DE PERSONALIDAD','3'),
					 ('','NO DAR CURSO A SOLICITUDES DE LOS SUBALTERNOS','3'),
					 ('','REPRESENTAR EN TERMINOS INDECOROSOS','3'),
					 ('','DESAUTORIZAR O QUITAR EL MANDO A UN SUBALTERNO','3'),
					 ('','INGRESAR O SALIR DEL INSTITUTO POR LUGARES INDEBIDOS PARA LOS FRANCOS','3'),
					 ('','ELUDIR EL CONDUCTO REGULAR','3'),
					 ('','ELUDIR ACTIVIDADES DEPORTIVAS DE INSTRUCCION CLASES','3'),
					 ('','PERMANECER EN LOS DORMITORIOS EN HORAS INDEBIDAS','3'),
					 ('','SERVIRSE ALIMENTOS DESTINADOS A OTROS ALUMNOS','3'),
					 ('','NO LEVANTARSE AL TOQUE DE DIANA','3'),
					 ('','ABUSO DE CONFIANZA','3'),
					 ('','ELUDIR LA SANCION FISICO IMPUESTO','3'),
					 ('','FINGIR ENFERMEDAD PARA FALTAR A CLASES INSTRUCCION O ACTIVIDADES DEPORTIVAS','3'),
					 ('','DESCONOCER SUS OBLIGACIONES EN LA GUARDIA','3'),
					 ('','NO PASAR CONSIGNAS','3'),
					 ('','ATRASARSE A COMPROMISOS DEL BATALLON SOCIALES CULTURALES EVENTOS DEPORTIVOS','3'),
					 ('','FALTA DE MORAL MILITAR','3'),
					 ('','CONTRAER DEUDAS CON LOS SUBALTERNOS','3'),
					 ('','PERMANECER EN AREAS INDEBIDAS','3'),
					 ('','NO OBSERVAR MEDIDAS DE SEGURIDAD AL MANEJAR EXPLOSIVOS ARMAMENTO MUNICION SI NO ES DELITO','3'),
					 ('','DISCUTIR AIRADAMENTE EN PRESENCIA DE SUPERIORES O SUBALTERNOS','3'),
					 ('','FALTA DE RESPETO CON EL UNIFORME','3'),
					 ('','DEMOSTRAR CONDUCTA INDECOROSA EN ACTOS PUBLICOS','3'),
					 ('','NO LLEVAR EL CORTE REGLAMENTARIO','3'),
					 ('','DAR PARTE FALSO','3'),
					 ('','PERMANECER SIN AUTORIZACION EN LAS INMEDIACIONES O DENTRO DEL PABELLON DE ALUMNAS Y ALUMNOS','3'),
					 ('','TOMARSE DE LA MANO DENTRO DE LAS INSTALACIONES DEL INSTITUTO CON UNA ALUMNA','3'),
					 ('','ADUCIR DIFERENCIAS DE GENERO PARA NO REALIZAR UN EJERCICIO','3'),
					 ('','REALIZAR DISCRIMINACION DE GENEROS','3'),
					 ('','REALIZAR INSINUACIONES AMOROSAS A UN SUPERIOR O SUBALTERNO','3'),
					 ('','FINGIR ENCONTRARSE CON SU PERIODO MENSTRUAL PARA ELUDIR ACTIVIDADES Y O SANCIONES','3'),
					 ('','EXCUSARSE DE CUMPLIR UNA SANCION POR ESTAR CON SU PERIODO MENSTRUAL','3'),
					 ('','NO LLEVAR EL TRAJE DE BAÑO REGLAMENTARIO','3'),
					 ('','DESCUIDADO CON SUS PRENDAS DE DOTACION','3'),
					 ('','NO CUMPLIR SUS OBLIGACIONES COMO CENTINELA DE GUARDIA','3'),
					 ('','NO CUMPLIR SUS OBLIGACIONES EN LA GUARDIA','3'),
					 ('','NO LLEVAR EL CORTE REGLAMENTARIO PARA DAMAS','3'),
					 ('','FALTA DE PULCRITUD EN EL LLENADO DE DOCUMENTOS','3'),
					 ('','DORMIR EN AULAS','3'),
					 ('','FALTA DE CONSIDERACION CON LOS CATEDRATICOS CIVILES','3'),
					 ('','ABANDONAR LAS AULAS SIN AUTORIZACION','3'),
					 ('','PORTAR EN AULAS MATERIAL PORNOGRAFICO','3'),
					 ('','FALTA DE PULCRITUD EN LOS TRABAJOS PRESENTADOS','3'),
					 ('','FALTA DE PULCRITUD EN EXAMENES','3'),
					 ('','ATRASARSE EN INGRESAR AL PABELLON DE ESTUDIOS','3'),
					 ('','NO CUMPLIR O ELUDIR LOS PERIODOS DE TIEMPO DESTINADOS A ESTUDIOS','3'),
					 ('','DESCUIDO CON EL ARMAMENTO','4'),
					 ('','DESCUIDADO CON LA LIMPIEZA DEL ARMAMENTO','4'),
					 ('','PROPAGAR RUMORES FALSOS','4'),
					 ('','FALTA DE HIDALGUIA','4'),
					 ('','FALTA DE FORMACION','4'),
					 ('','GUARDAR ARMAMENTO MUNICION EQUIPO Y MATERIAL EN LUGARES NO ESTABLECIDOS','4'),
					 ('','SACAR DEL INSTITUTO PRENDAS SIN AUTORIZACION ','4'),
					 ('','EXIGIR TRIBUTO','4'),
					 ('','RECIBIR O ENTREGAR LA GUARDIA INCORRECTAMENTE','4'),
					 ('','ENCUBRIR FALTAS','4'),
					 ('','OBLIGAR O EJERCER INFLUENCIAS NEGATIVAS SOBRE SUBALTERNOS','4'),
					 ('','ABUSO DE AUTORIDAD','4'),
					 ('','NEGAR A SUS FAMILIARES O SU LUGAR DE PROCEDENCIA','4'),
					 ('','VACIAR ARBITRARIAMENTE LA PISCINA','4'),
					 ('','FALTA DE CELO CON LA SEGURIDAD DEL INSTITUTO','4'),
					 ('','DAR PARTE FALSO CON PREMEDITACION','4'),
					 ('','ENCUBRIR LA AUSENCIA DE UN CAMARADA','4'),
					 ('','EXCEDERSE EN SANCIONES FISICAS','4'),
					 ('','HABLAR MAL DE UN CAMARADA EN SU AUSENCIA','4'),
					 ('','RECIBIR VISITAS EN HORAS INDEBIDAS SIN AUTORIZACION','4'),
					 ('','NO PRESENTARSE A LA AUTORIDAD MILITAR EN LAS VACACIONES O CUANDO SALE DE LA GUARNICION','4'),
					 ('','DEMOSTRAR FALTA DE MORALIDAD Y ETICA MILITAR','4'),
					 ('','PROTAGONIZAR PELEAS CON LOS CAMARADAS','4'),
					 ('','EXTRAVIAR PRENDAS O ARTICULOS DEL INSTITUTO','4'),
					 ('','LEVANTAR EN FALSO NOMBRE DE UN SUPERIOR','4'),
					 ('','PIROPEAR O INSULTAR DENTRO O FUERA DEL INSTITUTO A UNA ALUMNA O ALUMNO','4'),
					 ('','MANTENER FAMILIARIDAD CON SUBALTERNOS O SUPERIORES','4'),
					 ('','EXHIBIR ROPA INTERIOR Y PRENDAS INTIMAS','4'),
					 ('','BESARSE FUERA DEL INSTITUTO ENCONTRANDOSE CON UNIFORME','4'),
					 ('','PERMANECER EN AREAS PROHIBIDAS RESTRINGIDAS CON LA AGRAVANTE DE CONSIDERARSE COMO ABANDONO ARBITRARIO DEL INSTITUTO','4'),
					 ('','NO DAR PARTE DE ALGUN INCIDENTE EN EL PUESTO DE CENTINELA','4'),
					 ('','PRESENTAR TRABAJOS O EJERCICIOS PRACTICOS INCOMPLETOS O REALIZADOS INCORRECTAMENTE','4'),
					 ('','EXCEDERSE EN EL PERIODO DE TIEMPO ASIGNADO PARA LA REALIZACION DE EXAMENES PARCIALES Y FINALES','4'),
					 ('','TRANSITAR POR AREAS RESTRINGIDAS PARA EL PERSONAL DE ALUMNAS Y ALUMNOS','4'),
					 ('','VALERSE DE INFLUENCIAS INTERNAS O EXTERNAS PARA OBTENER PREBENDAS','5'),
					 ('','DESCONOCER EL NUMERO DE SU ARMA DE DOTACION','5'),
					 ('','SACAR DE LA SALA DE ARMAS UN FUSIL QUE NO LE CORRESPONDE','5'),
					 ('','PERMITIR LA PRESENCIA SIN AUTORIZACION DE PERSONAL CIVIL Y MILITAR EN AREAS RESTRINGIDAS','5'),
					 ('','MURMURAR EN RELACION A UN SUPERIOR','5'),
					 ('','FOMENTAR LA DISCORDIA Y LOS CHISMES','5'),
					 ('','TRATAR DE CONSEGUIR FAVORES DE LOS SUPERIORES A TRAVES LAS INDULGENCIAS Y SERVILISMO','5'),
					 ('','HACER RECLAMOS IRRESPETUOSOS','5'),
					 ('','MODIFICAR LAS ORDENES DE UN SUPERIOR MALICIOSAMENTE','5'),
					 ('','OCULTAR EL CONTAGIO DE ENFERMEDADES VENEREAS Y OTRAS','5'),
					 ('','EMPEÑAR PRENDAS EN LAS CANTINAS','5'),
					 ('','SORPRENDER LA BUENA FE DE UN SUPERIOR','5'),
					 ('','FALTAR AL RELEVO DE GUARDIA MAS DE 30 MINUTOS','5'),
					 ('','HACERSE REMPLAZAR EN LA GUARDIA SIN AUTORIZACION','5'),
					 ('','UTILIZAR TELEFONOS DEL COMANDO 2DO COMANDO JEFATURA DE ESTUDIOS SIN AUTORIZACION','5'),
					 ('','INGRESAR A LAS OFICINAS SIN AUTORIZACION','5'),
					 ('','EN CUBRIR UNA FALTA COMETIDA POR UN CAMARADA Y UN SUBALTERNO','5'),
					 ('','VESTIR TRAJE CIVIL SIN AUTORIZACION','5'),
					 ('','NO CUMPLIR UNA ORDEN VERBAL O ESCRITA','5'),
					 ('','FALTAR A LA VERDAD','5'),
					 ('','BURLAR LA VIGILANCIA DE LA GUARDIA','5'),
					 ('','INCORPORARSE CON ALIENTO A BEBIDAS ALCOHOLICAS','5'),
					 ('','TRATAR DE ENGAÑAR A UN SUPERIOR','5'),
					 ('','FALTAR A LA PALABRA EMPEÑADA','5'),
					 ('','DESLEALTAD','5'),
					 ('','NO CUMPLIR DISPOSICIONES CONTENIDAS EN LA ORDEN DEL DIA','5'),
					 ('','NO HACERSE ANOTAR UNA SANCION EN EL LIBRO DE DISCIPLINA','5'),
					 ('','FALTA DE RESPETO CON UN SUPERIOR O CATEDRATICO','5'),
					 ('','MANTENER RELACIONES SENTIMENTALES SUBALTERNOS CAMARADAS O SUPERIORES','5'),
					 ('','INTENTAR ACOSAR A UN SUPERIOR CAMARADA O SUBALTERNO','5'),
					 ('','BESARSE DENTRO DEL INSTITUTO','5'),
					 ('','INDUCIR A UN SUPERIOR O SUBALTERNO A REALIZAR ACTOS CONTRA LA MORAL Y LAS BUENAS COSTUMBRES','5'),
					 ('','EXHIBIRSE SENTIMENTALMENTE DE UNIFORME CON UN SUPERIOR CAMARADA O SUBALTERNO','5'),
					 ('','MANTENER CONVERSACIONES PRIVADAS CON ALUMNAS Y ALUMNOS EN AREAS AISLADAS Y EN PRIVADO','5'),
					 ('','REALIZAR CHISTES PIROPOS CONVERSACIONES DE CONTENIDO SEXUAL QUE DAÑEN LA DIGNIDAD DE UNA PERSONA ','5'),
					 ('','EL SUPERIOR O DEL MISMO CURSO APROVECHANDO SU GRADO POSICION CARGO O FUNCION REALICE MIRADAS MUECAS GESTOS LASCIVOS','5'),
					 ('','MANIFESTAR INSINUACIONES PARA ELUDIR ACTIVIDADES O SANCIONES','5'),
					 ('','VALERSE DE INFLUENCIAS PARA ELUDIR ACTIVIDADES O SANCIONES O CONSEGUIR ALGUN BENEFICIO','5'),
					 ('','NO GUARDAR LA POSTURA MILITAR EN ACONTECIMIENTOS SOCIALES CUANDO SE ENCUENTRAN DE UNIFORME','5'),
					 ('','NO GUARDAR LA COMPOSTURA EN ACTOS SOCIALES','5'),
					 ('','NO PRESENTARSE A EXAMENES SIN JUSTIFICACION ALGUNA','5'),
					 ('','REALIZAR ACTOS SEÑAS O GESTOS SOSPECHOSOS DURANTE LOS EXAMENES','5'),
					 ('','NO PRESENTAR TRABAJOS','5'),
					 ('','FALTAR A CLASES SIN AUTORIZACION','5'),
					 ('','ABANDONAR LAS CLASES SIN AUTORIZACION','5'),
					 ('','NO RETORNAR A CLASES DESPUES DE UN DESCANSO','5'),
					 ('','ALTERAR UNIFORME EN VACACIONES','6'),
					 ('','ABANDONAR SERVICIO INTERNO','6'),
					 ('','SALIR A LA CALLE ESTANDO ARRESTADO','6'),
					 ('','NO INCORPORARSE A CUMPLIR ARRESTO','6'),
					 ('','ABANDONO ARBITRARIO DEL INSTITUTO','6'),
					 ('','FALTA DE RESPETO CON LOS PROGENITORES','6'),
					 ('','NO SOBREPNERSE AL MIEDO','6'),
					 ('','FALTAR A LA GUARDIA','6'),
					 ('','ABANDONAR LA GUARDIA','6'),
					 ('','SUPLANTAR LA JERARQUIA DE UN SUPERIOR','6'),
					 ('','INTIMIDAR CON SANCIONES PARA LOGRAR RELACION SENTIMENTAL','6'),
					 ('','PERDIDA O EXTRAVIO DE ARMAMENTO','7'),
					 ('','VIOLENTAR CASILLEROS O CORRESPONDENCIA','7'),
					 ('','CONTRAER MATRIMONIO','7'),
					 ('','ENCONTRARSE EN ESTADO DE GRAVIDEZ  O HABER ABORTADO','7'),
					 ('','MANTENER RELACIONES SEXUALES ENTRE ALUMNOS','7'),
					 ('','CAMINAR SUGESTIVAMENTE INCITANDO AL APETITO SEXUAL','7'),
					 ('','PARTICIPAR TRAFICO O CONSUMO DE DROGAS ','7'),
					 ('','ABANDONAR EN MASA LAS INSTALACIONES DEL INSTITUTO','7'),
					 ('','REINCIDENTE A COMETER UNA FALTA POR MAS DE TRES VECES ','7'),
					 ('','FRAUDE EXAMENES','7'),
					 ('','ADQUIRIR O VENDER EXAMENES','7'),
					 ('','PLAGIO EN TRABAJPS PRACTICOS','7'),
					 ('','ACOSAR A UN SUPERIOR, CAMARADA O SUBALTERNO','7'),
					 ('','COMETER ACTOS INMORALES','7'),
					 ('','OBLIGAR AL ABANDONO DEL INSTITUTO A AUMNOS INFERIORES','7')";

		if (mysqli_query($con, $INSERT_FALTA_TEST)) {
			# code...
			echo "<br> - FALTAS TESTS INSERTADOS - <br>";
		}
	}
//-------------------------------tabla merito-----------------------------------
$TB_MERITO = "CREATE TABLE merito (
id_merito INT NOT NULL AUTO_INCREMENT,
nombre_merito VARCHAR(150),
puntos INT,
PRIMARY KEY(id_merito)
)";
if(mysqli_query($con, $TB_MERITO)){
	echo "<br> - TABLA MERITO CREADA - ";

	$INSERT_MERITO_TESTS = "INSERT INTO
		merito(id_merito, nombre_merito, puntos)
			VALUES ('','EQUIPO O INDIVIDUAL 1ER PUESTO','3'),
						 ('','EQUIPO O INDIVIDUAL 2DO PUESTO','2'),
						 ('','EQUIPO O INDIVIDUAL 3ER PUESTO','1'),
						 ('','JUGADOR DESTACADO','1'),
						 ('','GANAR CONCURSOS CULTURALES','2'),
						 ('','FINALISTA CONCURSO CULTURAL ORGANIZADO JEF ESTUDIOS','1'),
						 ('','PRESENTACION DE TRABAJOS INCLUIDOS EN REVISTAS BOLETINES Y PERIODICOS ','1'),
						 ('','FORMAR PARTE DEL ELENCO DE TEATRO','1'),
						 ('','DICTAR UNA CONFERENCIA DENTRO EL INSTITUTO','1'),
						 ('','PRIMER PUESTO EN EL MODULO','1.5'),
						 ('','SEGUNDO PUESTO EN EL MODULO','1'),
						 ('','TERCER PUESTO EN EL MODULO','0.5'),
						 ('','POR MODULO QUE TENGA E','5'),
						 ('','POR MODULO QUE TENGA MB','3'),
						 ('','PRIMER PUESTO CUADRO DE HONOR','5'),
						 ('','SEGUNDO PUESTO CUADRO DE HONOR','4'),
						 ('','TERCER PUESTO CUADRO DE HONOR','3'),
						 ('','CUARTO PUESTO CUADRO DE HONOR','2'),
						 ('','QUINTO PUESTO CUADRO DE HONOR','1'),
						 ('','TRABAJO SOBRESALIENTE INDIVIDUAL','2'),
						 ('','TRABAJO SOBRESALIENTE GRUPAL','1'),
						 ('','ACTOS DESTACADOS FORMACION MILITAR DE 2 PTOS','2'),
						 ('','ACTOS DESTACADOS FORMACION MILITAR DE 3 PTOS','3'),
						 ('','ACTOS DESTACADOS FORMACION MILITAR DE 4 PTOS','4'),
						 ('','ACTOS DESTACADOS FORMACION MILITAR DE 5 PTOS','5'),
						 ('','FELICITACION POR ORDEN DEL DIA POR CAPACIDAD DE MANDO','3'),
						 ('','FELICITACION POR ORDEN DEL DIA POR ESPIRITU DE CUERPO','3'),
						 ('','FELICITACION POR ORDEN DEL DIA POR VALOR','3'),
						 ('','FELICITACION POR ORDEN DEL DIA POR HONRADEZ','3'),
						 ('','FELICITACION POR ORDEN DEL DIA POR DESPRENDIMIENTO','3'),
						 ('','FELICITACION POR ORDEN DEL DIA POR LEALTAD','3'),
						 ('','FELICITACION POR ORDEN DEL DIA POR CAMARADERIA','3'),
						 ('','FELICITACION POR ORDEN DEL DIA POR ABNEGACION','3'),
						 ('','FELICITACION POR ORDEN DEL DIA POR ESPIRITU MILITAR','3'),
						 ('','FELICITACION POR ORDEN DEL DIA POR INICIATIVA','3'),
						 ('','FELICITACION COMANDO EMSE INDIVIDUAL','3'),
						 ('','FELICITACION COMANDO EMSE GRUPAL','1'),
						 ('','ASCENSOS AL GRADO DE ALUMNOS MAYOR','5'),
						 ('','ASCENSOS AL GRADO DE ALUMNO PRIMERO','3'),
						 ('','ASCENSOS AL GRADO DE ALUMNO SEGUNDO','2'),
						 ('','OBTENCION DE CORDON DORADO','5'),
						 ('','OBTENCION DE CORDON ROJO','5'),
						 ('','OBTENCION DE CORDON BLANCO','5'),
						 ('','OBTENCION DE CORDON AZUL','5'),
						 ('','OBTENCION DE CORDON CELESTE','5'),
						 ('','OBTENCION DE CORDON CELESTE Y BLANCO','5'),
						 ('','OBTENCION DE CORDON VERDE','5'),
						 ('','ABANDERADO DEL ESTANDARTE DEL INSTITUTO','5'),
						 ('','ABANDERADO DE LA BANDERA DE GUERRA','4'),
						 ('','ABANDERADO DE LAS BANDERAS DE LAS ARMAS','3'),
						 ('','DESIGNACION DE ESCOLTA AL ESTANDARTE DEL INSITUTO','3'),
						 ('','DESIGNACION DE ESCOLTA A LA BANDERA DE GUERRA','2'),
						 ('','CAMPEONATOS DEPARTAMENTALES INDIVIDUAL O EQUIPOS PRIMER PUESTO','5'),
						 ('','CAMPEONATOS DEPARTAMENTALES INDIVIDUAL O EQUIPOS SEGUNDO PUESTO','4'),
						 ('','CAMPEONATOS DEPARTAMENTALES INDIVIDUAL O EQUIPOS TERCER PUESTO','3'),
						 ('','CAMPEONATOS DEPARTAMENTALES INDIVIDUAL O EQUIPOS JUGADORES MAS DESTACADOS','2'),
						 ('','CAMPEONATOS NACIONALES INDIVIDUAL O EQUIPOS PRIMER PUESTO','6'),
						 ('','CAMPEONATOS NACIONALES INDIVIDUAL O EQUIPOS SEGUNDO PUESTO','5'),
						 ('','CAMPEONATOS NACIONALES INDIVIDUAL O EQUIPOS TERCER PUESTO','4'),
						 ('','CAMPEONATOS NACIONALES INDIVIDUAL O EQUIPOS JUGADORES MAS DESTACADOS','3'),
						 ('','CAMPEONATOS INTERNACIONALES INDIVIDUAL O EQUIPOS PRIMER PUESTO','10'),
						 ('','CAMPEONATOS INTERNACIONALES INDIVIDUAL O EQUIPOS SEGUNDO PUESTO','9'),
						 ('','CAMPEONATOS INTERNACIONALES INDIVIDUAL O EQUIPOS TERCER PUESTO','8'),
						 ('','CAMPEONATOS INTERNACIONALES INDIVIDUAL O EQUIPOS JUGADORES MAS DESTACADOS','7'),
						 ('','ACTIVIDADES SOCIALES CULTURALES EN CONCURSOS DEPARTAMENTALES','5'),
						 ('','ACTIVIDADES SOCIALES CULTURALES DEPARTAMENTALES DE REVISTAS O PUBLICACIONES','4'),
						 ('','ACTIVIDADES SOCIALES CULTURALES DEPARTAMENTALES EN DICTAR CONFERENCIAS FUERA DEL INSTITUTO','3'),
						 ('','ACTIVIDADES SOCIALES CULTURALES EN CONCURSOS NACIONALES','5'),
						 ('','ACTIVIDADES SOCIALES CULTURALES NACIONALES PRIMER PUESTO EN TORNEOS Y CONCURSOS','4'),
						 ('','ACTIVIDADES SOCIALES CULTURALES NACIONALES SEGUNDO PUESTO EN TORNEOS Y CONCURSOS','3'),
						 ('','ACTIVIDADES SOCIALES CULTURALES NACIONALES TERCER PUESTO EN TORNEOS Y CONCURSOS','3'),
						 ('','FELICITACIONES EXTERNAS DEL COMANDANTE DEL INSTITUTO','5'),
						 ('','FELICITACIONES EXTERNAS DE DEPARTAMENTOS DEL EM EJTO','5'),
						 ('','FELICITACIONES EXTERNAS DEL JEFE DE ESTADO MAYOR','6'),
						 ('','FELICITACIONES EXTERNAS DEL COMANDANTE DE EJERCITO','7'),
						 ('','FELICITACIONES EXTERNAS DEL COMANDO EN JEFE','8'),
						 ('','FELICITACIONES EXTERNAS DEL MINISTERIO DE DEFENSA','8'),
						 ('','FELICITACIONES EXTERNAS DE LA PRESIDENCIA DE LA REPUBLICA','10')";
}
if (mysqli_query($con, $INSERT_MERITO_TESTS)) {

	echo "<br> - MERITO TESTS INSERTADOS - <br>";
}
//-------------------------------TABLE ROL------------------------------------
	$TB_ROL = "CREATE TABLE rol (
		id_rol INT NOT NULL AUTO_INCREMENT,
		rol VARCHAR(50),
		descripcion VARCHAR(50),
		PRIMARY KEY(id_rol)
	)";

	if(mysqli_query($con, $TB_ROL)){
		echo "<br> - TABLA ROL CREADA - ";

		$INSERT_ROLES_TESTS = "INSERT INTO
			rol(id_rol, rol, descripcion)
				VALUES ('','Administrador','Administra todo el sistema disciplinario'),
							 ('','Encargado de Disciplina','Administra faltas y los reportes disciplinarios'),
							 ('','Jefe de Personal','Administra Instructores'),
							 ('','Instructor','Administra Sanciones'),
							 ('','Primero de Compañia','Administra Alumnos y Sanciones'),
							 ('','Alumno','Administra Hoja de Vida Personal')";

		if (mysqli_query($con, $INSERT_ROLES_TESTS)) {
			# code...
			echo "<br> - ROLES TESTS INSERTADOS - <br>";
		}

	}

//------------------------------TABLE USUARIO---------------------------------
	$TB_USER = "CREATE TABLE usuario (
		id_ci INT,
		id_grado INT,
		id_arma INT,
		nombre VARCHAR(50),
		paterno VARCHAR(50),
		materno VARCHAR(50),
		sexo VARCHAR(15),
		fecha_nac VARCHAR(50),
		lugar_nac VARCHAR(50),
		correo VARCHAR(50),
		celular INT,
		direccion VARCHAR(50),
		codigo_secreto VARCHAR(8),
		ci_tutor INT,
		total_puntos INT,
		calificacion_disciplinario DOUBLE,
		PRIMARY KEY(id_ci)
	)";

	if(mysqli_query($con, $TB_USER)){
		echo "<br> - TABLA USUARIO CREADA - ";

		$INSERT_USUARIOS_TESTS = "INSERT INTO
			usuario(id_ci, id_grado, id_arma, nombre, paterno, materno, sexo, fecha_nac, lugar_nac, correo, celular, direccion, codigo_secreto, ci_tutor, total_puntos, calificacion_disciplinario)
				VALUES ('3841712','1','1','JUAN','NUNEZ','SOTO','MASCULINO','04/25/2016','TIRAQUE','juan@gmail.com','78859698','AV NORTE','0','0','0','0'),
							 ('3841713','4','4','PEPE','AGUILAR','MARNELI','MASCULINO','04/25/2016','SACABA','pepe@gmail.com','74587478','AV NORTE','0','0','0','0'),
							 ('3841714','5','4','LUCAS','MELO','LOPEZ','MASCULINO','04/25/2016','TIRAQUE','lucas@gmail.com','74458596','AV NORTE','0','0','0','0'),
							 ('3841715','4','2','MARTIN','JUDAS','TORO','MASCULINO','04/25/2016','BENI','martin@gmail.com','74589632','AV NORTE','0','0','0','0'),
							 ('3841716','5','3','RODRIGO','MURILLO','PUERTA','MASCULINO','04/25/2016','SANTA CRUZ','rodrigo@gmail.com','85749632','AV CAP USTARIZ','0','0','0','0'),
							 ('3841735','7','3','HENRY','PORTILLO','RUEDA','MASCULINO','03/26/2016','ROBORE','portillo258@gmail.com','75125896','AV BLANO GALINDO','0','0','0','0'),
							 ('3841736','4','3','DONATO','KIPPES','MENDEZ','MASCULINO','12/06/2016','PUERTO SUAREZ','kpppess@gmail.com','75236987','AV BLANO GALINDO','0','0','0','0'),
							 ('3841737','5','3','GUSTAVO','PEREZ','TERNA','MASCULINO','05/10/2016','COBIJA','perez@gmail.com','74585621','AV BLANO GALINDO','0','0','0','0'),
							 ('3841738','2','3','ISRAEL','INTURIAS','CAMBE','MASCULINO','08/11/2016','BERMEJO','inturias@gmail.com','74185654','AV BLANO GALINDO','0','0','0','0'),

							 ('3841717','15','0','ANTONIO','SOLIZ','MESA','MASCULINO','04/25/1996','COBIJA','antonio@gmail.com','74125896','AV NORTE','4444','123','4','96,08'),
							 ('3841718','16','0','MIGUEL','MORALES','SORIA','MASCULINO','04/25/1996','ROBORE','miguel@gmail.com','72787975','AV EL VALLE','4444','456','1','99,02'),
							 ('3841719','16','0','LUIS','MORALES','ZARNES','MASCULINO','04/25/1998','SUCRE','miguel@gmail.com','74458596','AV CIRCUNVALACION','4444','456','3','97,06'),
							 ('3841720','17','0','MARCOS','MORALES','ZAPATA','MASCULINO','04/25/1999','ORURO','miguel@gmail.com','78524145','AV NORTE','4444','456','1','99,02'),
							 ('3841721','17','0','MAURICIO','NOGALES','SUAREZ','MASCULINO','04/25/1998','ANZALDO','mauri@gmail.com','74859632','AV SUECIA','4444','456','1','99,02'),
							 ('3841722','17','0','MILTON','PAREDES','RAMOS','MASCULINO','02/16/1998','COBIJA','mauri@gmail.com','5245896','AV BLANCO GALINDO','4444','456','0','100'),
							 ('3841723','17','0','LEONCIO','MORALES','ZAPATA','MASCULINO','04/25/1999','LA PAZ','miguel@gmail.com','78854512','AV NORTE','4444','456','0','100'),
							 ('3841724','15','0','JOSE','SANSIESTEBAN','MESA','MASCULINO','04/25/1996','COBIJA','antonio@gmail.com','74125896','AV NORTE','4444','123','1','99,02'),
							 ('3841725','15','0','LUAN','KYLE','MESA','MASCULINO','04/25/1996','COBIJA','antonio@gmail.com','74125896','AV NORTE','4444','123','2','98,04'),
							 ('3841726','15','0','LIMBERT','SUAREZ','DIARET','MASCULINO','04/25/1996','COBIJA','antonio@gmail.com','74125896','AV NORTE','4444','123','1','99,02'),
							 ('3841727','15','0','TOBIAS','LIMA','CORDOVA','MASCULINO','04/25/1996','COBIJA','antonio@gmail.com','74125896','AV NORTE','4444','123','1','99,02'),
							 ('3841728','16','0','MIGUEL','MORALES','VALDIVIA','MASCULINO','04/25/1996','ROBORE','miguel@gmail.com','72787975','AV EL VALLE','4444','456','1','99,02'),
							 ('3841729','16','0','JUMIOR','FERTO','PERNAN','MASCULINO','04/25/1996','ROBORE','miguel@gmail.com','72787975','AV EL VALLE','4444','456','1','99,02'),
							 ('3841730','16','0','PECRO','FIGUEROA','TERAN','MASCULINO','04/25/1996','ROBORE','miguel@gmail.com','72787975','AV EL VALLE','4444','456','1','99,02'),
							 ('3841731','17','0','JUAN CARLOS','MORALES','LOPEZ','MASCULINO','04/25/1999','LA PAZ','miguel@gmail.com','78854512','AV NORTE','4444','456','0','100'),
							 ('3841732','17','0','LEONARDO','DONATO','SAENZ','MASCULINO','04/25/1999','LA PAZ','miguel@gmail.com','78854512','AV NORTE','4444','456','0','100'),
							 ('3841733','15','0','CARLOS','SOLIZ','MONTES','MASCULINO','04/25/1999','LA PAZ','miguel@gmail.com','78854512','AV NORTE','4444','456','0','100'),
							 ('3841734','16','0','KEVIN','RENGEL','TATU','MASCULINO','04/25/1999','LA PAZ','miguel@gmail.com','78854512','AV NORTE','4444','456','0','100')";

		if (mysqli_query($con, $INSERT_USUARIOS_TESTS)) {
			# code...
			echo "<br> - USUARIOS TESTS INSERTADOS - <br>";
		}
	}

//-----------------------TABLE ASIGNAR USUARIO--------------------------------
	$TB_ASIG_USER = "CREATE TABLE asignar_usuario (
		id_usuario INT NOT NULL AUTO_INCREMENT,
		id_rol INT,
		id_ci INT,
		usuario_nombre VARCHAR(50),
		usuario_password VARCHAR(50),
		PRIMARY KEY(id_usuario)
	)";

	if(mysqli_query($con, $TB_ASIG_USER)){
		echo "<br> - TABLA ASIGNAR USUARIO CREADA - ";

		$INSERT_ASIG_USUARIOS_TESTS = "INSERT INTO
			asignar_usuario(id_usuario, id_rol, id_ci, usuario_nombre, usuario_password)
				VALUES ('','1','3841712','admin','admin'),
						 	 ('','2','3841713','disc','disc'),
						 	 ('','3','3841714','jefe','jefe'),
							 ('','4','3841715','inst','inst'),
							 ('','5','3841716','primer','primer'),
							 ('','6','3841717','alum','alum'),
							 ('','6','3841718','3841718','1818'),
							 ('','6','3841719','3841719','1919'),
							 ('','6','3841720','3841720','2020'),
							 ('','6','3841721','3841721','2121'),
							 ('','6','3841722','3841722','2222'),
							 ('','6','3841723','3841723','2323'),
							 ('','6','3841724','3841724','2424'),
							 ('','6','3841725','3841725','2525'),
							 ('','6','3841726','3841726','2626'),
							 ('','6','3841727','3841727','2727'),
							 ('','6','3841728','3841728','2828'),
							 ('','6','3841729','3841729','2929'),
							 ('','6','3841730','3841730','3030'),
							 ('','6','3841731','3841731','3131'),
							 ('','6','3841732','3841732','3232'),
							 ('','6','3841733','3841733','3333'),
							 ('','6','3841734','3841734','3434'),
							 ('','4','3841735','3841735','3535'),
							 ('','4','3841736','3841736','3636'),
							 ('','4','3841737','3841737','3737'),
							 ('','4','3841738','3841738','3838')";

		if (mysqli_query($con, $INSERT_ASIG_USUARIOS_TESTS)) {
			# code...
			echo "<br> - ASIGNAR USUARIOS TESTS INSERTADOS - <br>";
		}

	}

//-----------------------------TABLE ARMA-------------------------------------
	$sqlarma = "CREATE TABLE arma (
	id_arma INT NOT NULL AUTO_INCREMENT,
	arma VARCHAR(30),
	descripcion VARCHAR(50),
	PRIMARY KEY(id_arma)
	)";

	if(mysqli_query($con, $sqlarma)){
		echo "<br> - TABLA ARMA CREADA -";

		$INSERT_ARMAS_TEST = "INSERT INTO
			arma(id_arma,arma,descripcion)
				VALUES ('','INF.','INFANTERIA'),
							 ('','CAB.','CABALLERIA'),
							 ('','ART.','ARTILLERIA'),
							 ('','ING.','INGENIERIA'),
							 ('','COM.','COMUNICACIONES'),
							 ('','MAT. BEL.','MATERIAL BELICO'),
							 ('','INT.','INTENDENCIA'),
							 ('','MOT','MOTORES'),
							 ('','SAN.','SANIDAD'),
							 ('','AV. EJTO.','AVIACION DE EJERCITO')";

		if (mysqli_query($con, $INSERT_ARMAS_TEST)) {
			echo "<br> - ARMAS TESTS INSERTADOS - <br>";
		}

	}

//-----------------------------TABLA GRADO------------------------------------
	$sqlgrado="CREATE TABLE grado (
	id_grado INT NOT NULL AUTO_INCREMENT,
	grado VARCHAR(30),
	descripcion VARCHAR(50),
	PRIMARY KEY(id_grado)
	)";

	if(mysqli_query($con,$sqlgrado)){
		echo "<br> - TABLA GRADO CREADA -";

		$INSERT_GRADOS_TEST = "INSERT INTO
			grado(id_grado,grado,descripcion)
				VALUES ('','GRAL.','OFICIAL GENERAL'),
							 ('','CNL.','CORONEL'),
							 ('','TCNL.','TENIENTECORONEL'),
							 ('','MY.','MAYOR'),
							 ('','CAP.','CAPITAN'),
							 ('','TTE.','TENIENTE'),
							 ('','SBTTE.','OFICIAL SUBALTERNO'),
							 ('','SOF. MY.','SUBOFICIAL MAYOR'),
							 ('','SOF. 1RO','SUBOFICIAL PRIMERO'),
							 ('','SOF. 2DO','SUBOFICIAL SEGUNDO'),
							 ('','SOF. INCL.','SUBOFICIAL INICIAL'),
							 ('','SGTO. 1RO','SARGENTO PRIMERO'),
							 ('','SGTO. 2DO','SARGENTO SEGUNDO'),
							 ('','SGTO. INCL.','SARGENTO INICIAL'),
							 ('','AL. 1AM.','ALUMNO PRIMER AÑO MILITAR'),
							 ('','AL. 2AM.','ALUMNO SEGUNDO AÑO MILITAR'),
							 ('','AL. 3AM.','ALUMNO TERCER AÑO MILITAR')";

		if (mysqli_query($con, $INSERT_GRADOS_TEST)) {
			echo "<br> - GRADOS TESTS INSERTADOS - <br>";
		}

	}

//-----------------------------TABLA TUTOR------------------------------------
	$TB_TUTOR = "CREATE TABLE tutor (
	id_tutor INT NOT NULL AUTO_INCREMENT,
	ci_tutor INT,
	nombre_tutor VARCHAR(80),
	telefono_tutor INT,
	direccion_tutor VARCHAR(80),
	PRIMARY KEY(id_tutor)
	)";

	if(mysqli_query($con, $TB_TUTOR)){
		echo "<br> - TABLA TUTOR CREADA -";

		$INSERT_TUTOR = "INSERT INTO
			tutor(id_tutor,ci_tutor,nombre_tutor,telefono_tutor,direccion_tutor)
				VALUES ('','123','JUAN MENESES','77887766','AV BOLIVAR'),
							 ('','345','YURI BOSE','99443322','AV LA PAZ'),
							 ('','567','MARIBEL LOPEZ','33221111','AV CIRCUNVALACION'),
							 ('','891','GROVER SALINAS','33344455','AV JUNIN'),
							 ('','891','TOMAS BARRIENTOS','33344455','AV GALVEZ'),
							 ('','456','MERLIN GUTIERREZ','33344455','AV EJERCITO')";

		if (mysqli_query($con, $INSERT_TUTOR)) {
			echo "<br> - TUTORES TESTS INSERTADOS - <br>";
		}
	}

//----------------------------TABLA SANCION-----------------------------------
	$TB_SANCION = "CREATE TABLE sancion (
	id_sancion INT NOT NULL AUTO_INCREMENT,
	ci_instructor INT,
	ci_alumno INT,
	id_falta INT,
	id_grupo INT,
	puntos INT,
	tipo VARCHAR(5),
	fecha DATE NOT NULL,
	id_resolucion INT,
	PRIMARY KEY(id_sancion)
	)";

	if(mysqli_query($con, $TB_SANCION)){
		echo "<br> - TABLA SANCION CREADA - ";

		$INSERT_SANCIONES_TEST = "INSERT INTO
			sancion(id_sancion,ci_instructor,ci_alumno,id_falta,id_grupo,puntos,tipo,fecha,id_resolucion)
				VALUES ('','3841712','3841717','8','1','1','D','2016/10/21',NULL),
							 ('','3841712','3841717','8','1','1','D','2016/10/25',NULL),
							 ('','3841713','3841717','8','1','1','D','2016/10/31',NULL),
							 ('','3841714','3841717','23','1','1','D','2016/10/31',NULL),
							 ('','3841714','3841721','8','1','1','D','2016/11/01',NULL),
							 ('','3841714','3841720','8','1','1','D','2016/11/01',NULL),
							 ('','3841715','3841718','23','1','1','D','2016/11/02',NULL),
							 ('','3841716','3841719','8','1','1','D','2016/11/02',NULL),
							 ('','3841714','3841719','23','1','1','D','2016/11/03',NULL),
							 ('','3841714','3841719','23','1','1','D','2016/11/03',NULL),
							 ('','3841714','3841724','22','1','1','D','2016/11/03',NULL),
							 ('','3841714','3841725','23','1','1','D','2016/11/03',NULL),
							 ('','3841714','3841726','1','1','1','D','2016/11/03',NULL),
							 ('','3841714','3841727','3','1','1','D','2016/11/03',NULL),
							 ('','3841714','3841728','2','1','1','D','2016/11/03',NULL),
							 ('','3841714','3841729','4','1','1','D','2016/11/03',NULL),
							 ('','3841714','3841730','1','1','1','D','2016/11/03',NULL)";

			if (mysqli_query($con, $INSERT_SANCIONES_TEST)) {
				echo "<br> - SANCIONES TESTS INSERTADOS - <br>";
			}
	}

	//-----------------------------tabla resoluciones-----------------------
	$TB_RESOLUCION = "CREATE TABLE resoluciones(
	id_resolucion INT NOT NULL AUTO_INCREMENT,
	ci_alumno INT,
	nombre VARCHAR(50),
	titulo VARCHAR(50),
	contenido mediumblob,
	tipo VARCHAR(50),
	PRIMARY KEY(id_resolucion)
	)";

	if(mysqli_query($con, $TB_RESOLUCION)){
		echo "<br> - TABLA RESOLUCIONES CREADA - ";
	}
	mysqli_close($con);
}


crearBD();
crearTablas();
?>
